export interface InventoryItem {
  id: string;
  name: string;
  category: "PRIORITY_RESTOCK" | "PACKAGING" | "POWDER" | "FLAVOUR" | "OTHERS" | "KITCHEN" | "PASTE" | "BARANG_BASAH" | "CLEANING" | "MERCH";
  unit: string;
  isUrgent: boolean;
  notes?: string;
}

export const INVENTORY_CATEGORIES = {
  PRIORITY_RESTOCK: "🚨 PRIORITY RESTOCK",
  PACKAGING: "📦 PACKAGING",
  POWDER: "🧂 POWDER",
  FLAVOUR: "🍯 FLAVOUR / PUREE / DAVINCI",
  OTHERS: "📦 OTHERS",
  KITCHEN: "🥘 KITCHEN INGREDIENTS",
  PASTE: "🥫 PASTE / SAUCE",
  BARANG_BASAH: "🥬 BARANG BASAH",
  CLEANING: "🧼 CLEANING",
  MERCH: "🛍️ MERCH",
} as const;

export const INVENTORY_ITEMS: InventoryItem[] = [
  // PRIORITY RESTOCK
  {
    id: "priority_1",
    name: "Pati Kopi",
    category: "PRIORITY_RESTOCK",
    unit: "bottle",
    isUrgent: true,
  },
  {
    id: "priority_2",
    name: "Cup 22oz",
    category: "PRIORITY_RESTOCK",
    unit: "rolls",
    isUrgent: false,
  },
  {
    id: "priority_3",
    name: "Cup 16oz",
    category: "PRIORITY_RESTOCK",
    unit: "rolls",
    isUrgent: false,
  },
  {
    id: "priority_4",
    name: "Goodday Full Cream Milk",
    category: "PRIORITY_RESTOCK",
    unit: "ctn",
    isUrgent: false,
  },
  {
    id: "priority_5",
    name: "Gold Coin Susu Pekat",
    category: "PRIORITY_RESTOCK",
    unit: "ctn",
    isUrgent: false,
  },
  {
    id: "priority_6",
    name: "Straw 6mm",
    category: "PRIORITY_RESTOCK",
    unit: "ctn",
    isUrgent: false,
  },
  {
    id: "priority_7",
    name: "Straw 10mm",
    category: "PRIORITY_RESTOCK",
    unit: "ctn",
    isUrgent: false,
  },
  {
    id: "priority_8",
    name: "ValuePride Whipped Cream",
    category: "PRIORITY_RESTOCK",
    unit: "boxes",
    isUrgent: true,
  },

  // PACKAGING
  {
    id: "packaging_1",
    name: "Hot Cup 12oz",
    category: "PACKAGING",
    unit: "rolls",
    isUrgent: false,
  },
  {
    id: "packaging_2",
    name: "Hot Lid Cup",
    category: "PACKAGING",
    unit: "rolls",
    isUrgent: false,
  },
  {
    id: "packaging_3",
    name: "Plastic Tapau (Transparent)",
    category: "PACKAGING",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "packaging_4",
    name: "Tray Air",
    category: "PACKAGING",
    unit: "rolls",
    isUrgent: false,
  },
  {
    id: "packaging_5",
    name: "Plastic Wrap",
    category: "PACKAGING",
    unit: "rolls",
    isUrgent: false,
  },
  {
    id: "packaging_6",
    name: "Thermal Receipt",
    category: "PACKAGING",
    unit: "rolls",
    isUrgent: false,
  },
  {
    id: "packaging_7",
    name: "Terminal Receipt",
    category: "PACKAGING",
    unit: "rolls",
    isUrgent: false,
  },
  {
    id: "packaging_8",
    name: "Sticker Receipt",
    category: "PACKAGING",
    unit: "rolls",
    isUrgent: false,
  },
  {
    id: "packaging_9",
    name: "Plastik Sampah L",
    category: "PACKAGING",
    unit: "rolls",
    isUrgent: false,
  },
  {
    id: "packaging_10",
    name: "Plastik Sampah XL",
    category: "PACKAGING",
    unit: "rolls",
    isUrgent: true,
  },
  {
    id: "packaging_11",
    name: "Plastik Sampah XXL",
    category: "PACKAGING",
    unit: "rolls",
    isUrgent: true,
  },
  {
    id: "packaging_12",
    name: "Glove",
    category: "PACKAGING",
    unit: "boxes",
    isUrgent: false,
    notes: "M, L",
  },
  {
    id: "packaging_13",
    name: "Paper Tray (Large)",
    category: "PACKAGING",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "packaging_14",
    name: "Paper Tray (Small)",
    category: "PACKAGING",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "packaging_15",
    name: "Food Box",
    category: "PACKAGING",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "packaging_16",
    name: "Bowl Laksa (26oz)",
    category: "PACKAGING",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "packaging_17",
    name: "Bowl Laksa Lid",
    category: "PACKAGING",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "packaging_18",
    name: "Soup Bowl",
    category: "PACKAGING",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "packaging_19",
    name: "Paper Bag (Toast)",
    category: "PACKAGING",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "packaging_20",
    name: "Bihun Goreng Paper",
    category: "PACKAGING",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "packaging_21",
    name: "Nasi Lemak Paper",
    category: "PACKAGING",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "packaging_22",
    name: "Garfu Nasi Lemak",
    category: "PACKAGING",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "packaging_23",
    name: "Sudu Nasi Lemak",
    category: "PACKAGING",
    unit: "ctn",
    isUrgent: false,
    notes: "1 ctn (40 packets) + 10 packets loose",
  },
  {
    id: "packaging_24",
    name: "Sudu Soft Boil",
    category: "PACKAGING",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "packaging_25",
    name: "Straw Kecil (6mm)",
    category: "PACKAGING",
    unit: "ctn",
    isUrgent: false,
    notes: "4 ctn + loose stock in cabinet",
  },
  {
    id: "packaging_26",
    name: "Straw Besar (10mm)",
    category: "PACKAGING",
    unit: "packets",
    isUrgent: false,
    notes: "54 packets loose in cabinet",
  },
  {
    id: "packaging_27",
    name: "Paper Bag (Kecil)",
    category: "PACKAGING",
    unit: "bundles",
    isUrgent: false,
  },
  {
    id: "packaging_28",
    name: "Paper Bag (Besar)",
    category: "PACKAGING",
    unit: "ctn",
    isUrgent: false,
  },
  {
    id: "packaging_29",
    name: "Soft Boil Container",
    category: "PACKAGING",
    unit: "piece",
    isUrgent: false,
  },

  // POWDER
  {
    id: "powder_1",
    name: "Cocoa Powder",
    category: "POWDER",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "powder_2",
    name: "Vanilla Powder",
    category: "POWDER",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "powder_3",
    name: "Matcha Powder",
    category: "POWDER",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "powder_4",
    name: "Creamer Powder",
    category: "POWDER",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "powder_5",
    name: "Taro Powder",
    category: "POWDER",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "powder_6",
    name: "Peach Tea Powder",
    category: "POWDER",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "powder_7",
    name: "Mix Powder",
    category: "POWDER",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "powder_8",
    name: "Milk Tea Powder",
    category: "POWDER",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "powder_9",
    name: "Cheese Powder",
    category: "POWDER",
    unit: "piece",
    isUrgent: false,
  },

  // FLAVOUR / PUREE / DAVINCI
  {
    id: "flavour_1",
    name: "Strawberry Puree 2.1kg",
    category: "FLAVOUR",
    unit: "tubs",
    isUrgent: false,
  },
  {
    id: "flavour_2",
    name: "Davinci Salted Caramel",
    category: "FLAVOUR",
    unit: "bottles",
    isUrgent: false,
  },
  {
    id: "flavour_3",
    name: "Davinci Chocolate",
    category: "FLAVOUR",
    unit: "bottles",
    isUrgent: false,
  },
  {
    id: "flavour_4",
    name: "Davinci Butterscotch",
    category: "FLAVOUR",
    unit: "bottles",
    isUrgent: false,
  },
  {
    id: "flavour_5",
    name: "Buttermilk Flavour",
    category: "FLAVOUR",
    unit: "bottles",
    isUrgent: false,
    notes: "2kg",
  },
  {
    id: "flavour_6",
    name: "Strawberry Flavour",
    category: "FLAVOUR",
    unit: "bottles",
    isUrgent: false,
  },
  {
    id: "flavour_7",
    name: "Sugar Syrup",
    category: "FLAVOUR",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "flavour_8",
    name: "Coconut Syrup",
    category: "FLAVOUR",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "flavour_9",
    name: "Jasmine Syrup",
    category: "FLAVOUR",
    unit: "piece",
    isUrgent: false,
  },

  // OTHERS
  {
    id: "others_1",
    name: "Biskut Crumbs",
    category: "OTHERS",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "others_2",
    name: "Brown Sugar Jelly",
    category: "OTHERS",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "others_3",
    name: "Agar Jelly",
    category: "OTHERS",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "others_4",
    name: "Coconut Flakes",
    category: "OTHERS",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "others_5",
    name: "Mineral Water",
    category: "OTHERS",
    unit: "ctn",
    isUrgent: false,
  },
  {
    id: "others_6",
    name: "Tisu",
    category: "OTHERS",
    unit: "packets",
    isUrgent: false,
  },

  // KITCHEN INGREDIENTS
  {
    id: "kitchen_1",
    name: "Chicken Floss",
    category: "KITCHEN",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "kitchen_2",
    name: "Bread",
    category: "KITCHEN",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "kitchen_3",
    name: "Bun",
    category: "KITCHEN",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "kitchen_4",
    name: "Beras",
    category: "KITCHEN",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "kitchen_5",
    name: "Bihun",
    category: "KITCHEN",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "kitchen_6",
    name: "Telur Kampung",
    category: "KITCHEN",
    unit: "papan",
    isUrgent: false,
  },
  {
    id: "kitchen_7",
    name: "Telur Grade C",
    category: "KITCHEN",
    unit: "papan",
    isUrgent: false,
  },
  {
    id: "kitchen_8",
    name: "Ikan Bilis",
    category: "KITCHEN",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "kitchen_9",
    name: "Kacang Tanah (Nasi Lemak)",
    category: "KITCHEN",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "kitchen_10",
    name: "Kacang Tanah (Ground)",
    category: "KITCHEN",
    unit: "packet",
    isUrgent: false,
  },
  {
    id: "kitchen_11",
    name: "Indomie",
    category: "KITCHEN",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "kitchen_12",
    name: "Mee Kuning",
    category: "KITCHEN",
    unit: "piece",
    isUrgent: true,
  },

  // PASTE / SAUCE
  {
    id: "paste_1",
    name: "Tomyam Paste",
    category: "PASTE",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "paste_2",
    name: "Nyonya Curry Laksa",
    category: "PASTE",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "paste_3",
    name: "Meehoon Sauce",
    category: "PASTE",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "paste_4",
    name: "Spicy Tomato Mayo",
    category: "PASTE",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "paste_5",
    name: "Tuna Mayo (1kg)",
    category: "PASTE",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "paste_6",
    name: "Sambal Nasi Lemak (3kg)",
    category: "PASTE",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "paste_7",
    name: "Mushroom Soup",
    category: "PASTE",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "paste_8",
    name: "Sambal Cuttlefish",
    category: "PASTE",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "paste_9",
    name: "Rendang (Ayam)",
    category: "PASTE",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "paste_10",
    name: "Rendang (Daging)",
    category: "PASTE",
    unit: "packets",
    isUrgent: false,
  },

  // BARANG BASAH
  {
    id: "barang_1",
    name: "Daun Pandan",
    category: "BARANG_BASAH",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "barang_2",
    name: "Butter",
    category: "BARANG_BASAH",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "barang_3",
    name: "Timun Jepun",
    category: "BARANG_BASAH",
    unit: "packet",
    isUrgent: false,
  },
  {
    id: "barang_4",
    name: "Kubis",
    category: "BARANG_BASAH",
    unit: "biji",
    isUrgent: false,
  },
  {
    id: "barang_5",
    name: "Nenas",
    category: "BARANG_BASAH",
    unit: "biji",
    isUrgent: false,
  },
  {
    id: "barang_6",
    name: "Mayonis Kewpie",
    category: "BARANG_BASAH",
    unit: "packet",
    isUrgent: false,
  },
  {
    id: "barang_7",
    name: "Lettuce",
    category: "BARANG_BASAH",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "barang_8",
    name: "Tomato",
    category: "BARANG_BASAH",
    unit: "packet",
    isUrgent: false,
  },
  {
    id: "barang_9",
    name: "Daun Pisang Alas",
    category: "BARANG_BASAH",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "barang_10",
    name: "Udang Frozen",
    category: "BARANG_BASAH",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "barang_11",
    name: "Fish Cake",
    category: "BARANG_BASAH",
    unit: "packets",
    isUrgent: false,
  },
  {
    id: "barang_12",
    name: "Halia",
    category: "BARANG_BASAH",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "barang_13",
    name: "Majerin Planta",
    category: "BARANG_BASAH",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "barang_14",
    name: "Santan",
    category: "BARANG_BASAH",
    unit: "kotak kecil",
    isUrgent: false,
  },
  {
    id: "barang_15",
    name: "Jagung Tin",
    category: "BARANG_BASAH",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "barang_16",
    name: "Ajinomoto",
    category: "BARANG_BASAH",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "barang_17",
    name: "Garam",
    category: "BARANG_BASAH",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "barang_18",
    name: "Kicap",
    category: "BARANG_BASAH",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "barang_19",
    name: "Pepper",
    category: "BARANG_BASAH",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "barang_20",
    name: "Minyak Masak",
    category: "BARANG_BASAH",
    unit: "piece",
    isUrgent: true,
  },

  // CLEANING
  {
    id: "cleaning_1",
    name: "Sabun Lantai",
    category: "CLEANING",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "cleaning_2",
    name: "Sabun Serbuk",
    category: "CLEANING",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "cleaning_3",
    name: "Sabun Pinggan",
    category: "CLEANING",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "cleaning_4",
    name: "Serai Wangi",
    category: "CLEANING",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "cleaning_5",
    name: "Asid Lantai",
    category: "CLEANING",
    unit: "piece",
    isUrgent: true,
  },
  {
    id: "cleaning_6",
    name: "Span",
    category: "CLEANING",
    unit: "packet",
    isUrgent: false,
  },

  // MERCH
  {
    id: "merch_1",
    name: "KS Signature Tumbler",
    category: "MERCH",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "merch_2",
    name: "YoGood Tumbler",
    category: "MERCH",
    unit: "piece",
    isUrgent: false,
    notes: "N/A",
  },
  {
    id: "merch_3",
    name: "Sipter Tumbler - Yellow",
    category: "MERCH",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "merch_4",
    name: "Sipter Tumbler - Green",
    category: "MERCH",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "merch_5",
    name: "Cuppy (Trio Bestie)",
    category: "MERCH",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "merch_6",
    name: "Kachaw Combo",
    category: "MERCH",
    unit: "piece",
    isUrgent: false,
  },
  {
    id: "merch_7",
    name: "Bestie Stickers",
    category: "MERCH",
    unit: "pack",
    isUrgent: false,
  },
];
